spring:
  application:
    name: assemblyops-api
  datasource:
    url: jdbc:postgresql://localhost:5432/assemblyops
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.assemblyops.api.config.PrismaNamingStrategy
    open-in-view: false

server:
  port: 4001
