//
//  CreateShiftSheet.swift
//  AssemblyOps
//
//  Created by Jorge Villeda on 3/1/26.
//

// MARK: - Create Shift Sheet
//
// Modal form for creating or editing a shift within a session.
// Uses free-form time pickers (not constrained to session program times)
// since departments like Attendant and Parking start duty
// well before program sessions begin.
//
// Fields:
//   - Required: Start Time, End Time (name auto-generated by backend)
//   - Context: Session name, Post name (read-only)
//

import SwiftUI

struct CreateShiftSheet: View {
    let sessionId: String
    let postId: String
    let sessionName: String
    let postName: String?
    @ObservedObject var viewModel: ShiftManagementViewModel

    /// If set, the sheet is in edit mode for this shift
    var editingShift: ShiftItem? = nil

    @Environment(\.dismiss) private var dismiss
    @Environment(\.colorScheme) var colorScheme

    @State private var startTime = Date()
    @State private var endTime = Date()
    @State private var isSubmitting = false

    private var isEditing: Bool { editingShift != nil }

    private var isFormValid: Bool {
        endTime > startTime
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: AppTheme.Spacing.xl) {
                    sessionInfoCard
                    timePickerCard
                    submitButton
                }
                .screenPadding()
                .padding(.top, AppTheme.Spacing.l)
                .padding(.bottom, AppTheme.Spacing.xxl)
            }
            .themedBackground(scheme: colorScheme)
            .navigationTitle(isEditing ? "shift.edit".localized : "shift.create".localized)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("common.cancel".localized) { dismiss() }
                }
            }
            .onAppear { prepopulateIfEditing() }
        }
    }

    // MARK: - Session Info Card

    private var sessionInfoCard: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.s) {
            SectionHeaderLabel(icon: "calendar", title: "shift.session".localized)
            Text(sessionName)
                .font(AppTheme.Typography.bodyMedium)
                .foregroundStyle(.primary)
            if let postName = postName {
                HStack(spacing: AppTheme.Spacing.xs) {
                    Image(systemName: "mappin.and.ellipse")
                        .font(AppTheme.Typography.caption)
                    Text(postName)
                        .font(AppTheme.Typography.caption)
                }
                .foregroundStyle(AppTheme.textSecondary(for: colorScheme))
            }
        }
        .cardPadding()
        .themedCard(scheme: colorScheme)
    }

    // MARK: - Time Picker Card

    private var timePickerCard: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.m) {
            SectionHeaderLabel(icon: "clock", title: "shift.times".localized)

            VStack(spacing: AppTheme.Spacing.m) {
                DatePicker(
                    "shift.startTime".localized,
                    selection: $startTime,
                    displayedComponents: .hourAndMinute
                )
                .font(AppTheme.Typography.body)

                DatePicker(
                    "shift.endTime".localized,
                    selection: $endTime,
                    displayedComponents: .hourAndMinute
                )
                .font(AppTheme.Typography.body)

                if endTime <= startTime {
                    HStack(spacing: AppTheme.Spacing.xs) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundStyle(AppTheme.StatusColors.warning)
                        Text("shift.timeError".localized)
                            .font(AppTheme.Typography.caption)
                            .foregroundStyle(AppTheme.StatusColors.warning)
                    }
                }
            }
        }
        .cardPadding()
        .themedCard(scheme: colorScheme)
    }

    // MARK: - Submit Button

    private var submitButton: some View {
        Button {
            Task { await submit() }
        } label: {
            Group {
                if isSubmitting {
                    ProgressView()
                        .tint(.white)
                } else {
                    Text(isEditing ? "shift.update".localized : "shift.create".localized)
                }
            }
            .frame(maxWidth: .infinity)
            .frame(height: AppTheme.ButtonHeight.large)
            .font(AppTheme.Typography.bodyMedium)
            .foregroundStyle(.white)
            .background(isFormValid ? DepartmentColor.color(for: "ATTENDANT") : DepartmentColor.color(for: "ATTENDANT").opacity(0.4))
            .clipShape(RoundedRectangle(cornerRadius: AppTheme.CornerRadius.button))
        }
        .disabled(!isFormValid || isSubmitting)
    }

    // MARK: - Actions

    private func submit() async {
        isSubmitting = true

        let startStr = formatTime(startTime)
        let endStr = formatTime(endTime)

        if let shift = editingShift {
            await viewModel.updateShift(
                id: shift.id,
                startTime: startStr,
                endTime: endStr
            )
        } else {
            await viewModel.createShift(
                sessionId: sessionId,
                postId: postId,
                startTime: startStr,
                endTime: endStr
            )
        }

        isSubmitting = false

        if viewModel.error == nil {
            HapticManager.shared.success()
            dismiss()
        } else {
            HapticManager.shared.error()
        }
    }

    private func prepopulateIfEditing() {
        guard let shift = editingShift else { return }
        startTime = parseTimeField(shift.startTime) ?? Date()
        endTime = parseTimeField(shift.endTime) ?? Date()
    }

    /// Format Date to "HH:mm" string for the backend
    private func formatTime(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm"
        return formatter.string(from: date)
    }

    /// Parse a time field that could be ISO 8601 DateTime or "HH:mm"
    private func parseTimeField(_ timeString: String) -> Date? {
        // Try ISO 8601 first (backend returns "1970-01-01T07:45:00.000Z")
        if let date = DateUtils.parseISO8601(timeString) {
            // Extract hour/minute and create a Date for today's time picker
            let calendar = Calendar.current
            let components = calendar.dateComponents([.hour, .minute], from: date)
            var todayComponents = calendar.dateComponents([.year, .month, .day], from: Date())
            todayComponents.hour = components.hour
            todayComponents.minute = components.minute
            return calendar.date(from: todayComponents)
        }

        // Fallback: "HH:mm" format
        let parts = timeString.split(separator: ":")
        guard parts.count >= 2,
              let hour = Int(parts[0]),
              let minute = Int(parts[1]) else {
            return nil
        }

        let calendar = Calendar.current
        var components = calendar.dateComponents([.year, .month, .day], from: Date())
        components.hour = hour
        components.minute = minute
        return calendar.date(from: components)
    }
}

#Preview {
    CreateShiftSheet(
        sessionId: "session-1",
        postId: "post-1",
        sessionName: "Saturday Morning",
        postName: "Main Entrance",
        viewModel: ShiftManagementViewModel()
    )
}

#Preview("Edit Mode") {
    CreateShiftSheet(
        sessionId: "session-1",
        postId: "post-1",
        sessionName: "Saturday Morning",
        postName: "Main Entrance",
        viewModel: ShiftManagementViewModel(),
        editingShift: ShiftItem(
            id: "shift-1",
            sessionId: "session-1",
            postId: "post-1",
            name: "Exterior Shift 1",
            startTime: "07:45",
            endTime: "08:45",
            sessionName: "Saturday Morning",
            postName: "Main Entrance",
            createdAt: nil,
            createdByName: nil,
            assignments: []
        )
    )
}
