/**
 * Credential Generation Utilities
 *
 * User ID Format (global, permanent):
 *   - userId: 6 alphanumeric chars, no prefix — e.g. "A7X9K2"
 *   - Assigned once at User creation, never changes
 *   - Volunteers share this ID with overseers to be added to events
 *
 * EventVolunteer Credential Format (per-event, generated by overseer):
 *   - volunteerId: 6 alphanumeric chars — e.g. "B3M8P1"
 *   - token: 8 alphanumeric chars — e.g. "X4K2R9JH"
 *   - Printed on volunteer cards for event-day login
 *
 * Character Set:
 *   Uses ABCDEFGHJKLMNPQRSTUVWXYZ23456789 (removes ambiguous: 0, O, I, 1)
 *   Makes credentials easy to read/type from printed cards.
 *
 * Security:
 *   - Plain token is ONLY returned once (at creation)
 *   - Only the bcrypt hash (tokenHash) is stored in the database
 */
import crypto from 'crypto';
import bcrypt from 'bcryptjs';

// Characters for ID/token generation (removed confusing: I, O, 0, 1)
const ID_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

// ============================================
// USER ID (global, permanent identity)
// ============================================

/**
 * Generate a 6-char alphanumeric User ID
 * This is the user's permanent global identity — assigned at account creation
 * Example: "A7X9K2"
 */
export function generateUserId(): string {
  let id = '';
  for (let i = 0; i < 6; i++) {
    id += ID_CHARS.charAt(crypto.randomInt(ID_CHARS.length));
  }
  return id;
}

// ============================================
// EVENT VOLUNTEER CREDENTIALS (per-event)
// ============================================

/**
 * Generate a 6-char per-event volunteer ID
 * Used for EventVolunteer records (the printed-card credential system)
 * Example: "B3M8P1"
 */
export function generateEventVolunteerId(): string {
  let id = '';
  for (let i = 0; i < 6; i++) {
    id += ID_CHARS.charAt(crypto.randomInt(ID_CHARS.length));
  }
  return id;
}

/**
 * Generate a secure 8-char token for event-day login
 * Combined with volunteerId, provides sufficient entropy for auth
 * Example: "X4K2R9JH"
 */
export function generateToken(): string {
  let token = '';
  for (let i = 0; i < 8; i++) {
    token += ID_CHARS.charAt(crypto.randomInt(ID_CHARS.length));
  }
  return token;
}

/**
 * Hash a token using bcrypt for secure storage
 */
export async function hashToken(token: string): Promise<string> {
  return bcrypt.hash(token, 10);
}

/**
 * Verify a plain token against its bcrypt hash
 */
export async function verifyToken(token: string, hash: string): Promise<boolean> {
  return bcrypt.compare(token, hash);
}

// ============================================
// TOKEN ENCRYPTION (delegates to encryption.ts)
// ============================================
import { encryptField, decryptField } from './encryption.js';

/**
 * Encrypt a volunteer token using AES-256-GCM
 * Stored so overseers can retrieve credentials if a volunteer loses them
 */
export function encryptToken(plainToken: string): string {
  return encryptField(plainToken);
}

/**
 * Decrypt an AES-256-GCM encrypted token
 */
export function decryptToken(encryptedToken: string): string {
  return decryptField(encryptedToken);
}
